cnn: 'vit'
transformation:
  resize:
    w: 356
    h: 356
  std:
    - 0.5
    - 0.5
    - 0.5
  mean:
    - 0.5
    - 0.5
    - 0.5
  rhfp: 0.5
  rvfp: 0.5
  rrd: 15
  image_size:
    w: 224
    h: 224
pretrained: True
embed_size: 256 
hidden_size: 512
num_layers: 4
lr: 0.0001
num_workers: 4
batch_size: 
  train: 64
  test: 1

