cnn: 'vit'
transformation:
  resize:
    w: 356
    h: 356
  std:
    - 0.5
    - 0.5
    - 0.5
  mean:
    - 0.5
    - 0.5
    - 0.5
  rhfp: 0.2
  rvfp: 0.2
  rrd: 90
  image_size:
    w: 224
    h: 224
pretrained: True
embed_size: 128 
hidden_size: 128
num_layers: 1
lr: 0.0001
num_workers: 4
batch_size: 
  train: 64
  test: 1

